- hosts: all
  become: yes
  tasks:
    # Google Chrome
    - name: Download Google Chrome .deb package
      ansible.builtin.get_url:
        url: https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        dest: /tmp/google-chrome-stable_current_amd64.deb

    - name: Install Google Chrome
      ansible.builtin.apt:
        deb: /tmp/google-chrome-stable_current_amd64.deb
        update_cache: yes

    # Brave Browser
    - name: Add Brave browser repository key
      ansible.builtin.apt_key:
        url: https://brave-browser-apt-release.s3.brave.com/brave-core.asc
        state: present
        keyring: /etc/apt/trusted.gpg.d/brave.gpg

    - name: Add Brave browser APT source
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main'
        state: present

    - name: Install Brave browser
      ansible.builtin.apt:
        name: brave-browser
        state: present
        update_cache: yes

    # Chromium
    - name: Install Chromium
      community.general.flatpak:
        name: org.chromium.Chromium
        state: present
        remote: flathub

    # Opera
    - name: Add Opera browser repository key
      ansible.builtin.apt_key:
        url: https://deb.opera.com/archive.key
        state: present
        keyring: /etc/apt/trusted.gpg.d/opera.gpg

    - name: Add Opera browser APT source
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://deb.opera.com/opera-stable/ stable non-free'
        state: present

    - name: Install Opera browser
      ansible.builtin.apt:
        name: opera-stable
        state: present
        update_cache: yes

    # Microsoft Edge
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - software-properties-common
          - apt-transport-https
          - ca-certificates
          - curl
        state: present

    - name: Add Microsoft GPG key
      ansible.builtin.shell: |
        curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-edge-archive-keyring.gpg --yes
      args:
        executable: /bin/bash

    - name: Add Microsoft Edge repository
      ansible.builtin.apt_repository:
        repo: 'deb [signed-by=/usr/share/keyrings/microsoft-edge-archive-keyring.gpg] https://packages.microsoft.com/repos/edge stable main'
        state: present

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Microsoft Edge
      ansible.builtin.apt:
        name: microsoft-edge-stable
        state: present

    # Responsively App
    - name: Install dependencies
      ansible.builtin.apt:
        name: curl
        state: present

    - name: Download Responsively AppImage
      ansible.builtin.get_url:
        url: https://github.com/responsively-org/responsively-app-releases/releases/download/v1.15.0/ResponsivelyApp-1.15.0.AppImage
        dest: /usr/local/bin/ResponsivelyApp.AppImage
        mode: '0755'

    - name: Download Responsively icon
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/responsively-org/responsively-app/refs/heads/main/desktop-app/assets/icons/256x256.png
        dest: /usr/share/icons/responsively.png
        mode: '0644'

    - name: Create Desktop Entry for Responsively
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Name=ResponsivelyApp
          Exec=/usr/local/bin/ResponsivelyApp.AppImage
          Icon=/usr/share/icons/responsively.png
          Type=Application
          Categories=Development;
          Terminal=false
        dest: /usr/share/applications/responsively.desktop
        mode: '0644'

    # Tor Browser
    - name: Install Tor Browser Launcher
      community.general.flatpak:
        name: org.torproject.torbrowser-launcher
        state: present
        remote: flathub
