---
- name: Install 3D modeling and slicing tools
  hosts: all
  become: true
  tasks:
    # Install 3D modeling tools
    - name: Install 3D modeling tools
      ansible.builtin.apt:
        pkg:
          - blender # 3D creation suite
          - meshlab # 3D mesh processing software
          - openscad # The Programmers Solid 3D CAD Modeller
          - clang-format # Tool to format C/C++/Obj-C/Openscad code
        state: present
        
    # Install Discord via Flatpak (more portable and updated on Flathub)
    - name: Install Freecad
      community.general.flatpak:
        name: org.freecad.FreeCAD
        state: present
        remote: flathub

    # Install OrcaSlicer
    - name: Install dependencies for OrcaSlicer
      ansible.builtin.apt:
        pkg:
          - curl
        state: present

    - name: Download OrcaSlicer AppImage
      ansible.builtin.get_url:
        url: https://github.com/OrcaSlicer/OrcaSlicer/releases/download/v2.3.1/OrcaSlicer_Linux_AppImage_Ubuntu2404_V2.3.1.AppImage
        dest: /usr/local/bin/OrcaSlicer.AppImage
        mode: '0755'

    - name: Download OrcaSlicer icon
      ansible.builtin.get_url:
        url: https://github.com/SoftFever/OrcaSlicer/raw/refs/heads/main/resources/Icon.icns
        dest: /usr/share/icons/orcaslicer.png

    - name: Create Desktop Entry for OrcaSlicer
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Name=OrcaSlicer
          Exec=/usr/local/bin/OrcaSlicer.AppImage
          Icon=/usr/share/icons/orcaslicer.png
          Type=Application
          Categories=Graphics;
          Terminal=false
        dest: /usr/share/applications/orcaslicer.desktop
        mode: '0644'
