---
- name: Install 3D modeling and slicing tools
  hosts: all
  become: true
  tasks:
    # Install 3D modeling tools
    - name: Install 3D modeling tools
      ansible.builtin.apt:
        pkg:
          - freecad # 3D CAD modeler
          - openscad # The Programmers Solid 3D CAD Modeller
        state: present

    # Install OrcaSlicer
    - name: Install dependencies for OrcaSlicer
      ansible.builtin.apt:
        pkg:
          - curl
        state: present

    - name: Download OrcaSlicer AppImage
      ansible.builtin.get_url:
        url: https://github.com/SoftFever/OrcaSlicer/releases/download/v2.2.0/OrcaSlicer_Linux_V2.2.0.AppImage
        dest: /usr/local/bin/OrcaSlicer.AppImage
        mode: '0755'

    - name: Download OrcaSlicer icon
      ansible.builtin.get_url:
        url: https://github.com/SoftFever/OrcaSlicer/raw/refs/heads/main/resources/Icon.icns
        dest: /usr/share/icons/orcaslicer.png

    - name: Create Desktop Entry for OrcaSlicer
      ansible.builtin.copy:
        content: |
          [Desktop Entry]
          Name=OrcaSlicer
          Exec=/usr/local/bin/OrcaSlicer.AppImage
          Icon=/usr/share/icons/orcaslicer.png
          Type=Application
          Categories=Graphics;
          Terminal=false
        dest: /usr/share/applications/orcaslicer.desktop
        mode: '0644'
