---
- name: Install communication apps
  hosts: all
  become: true
  tasks:
    # Install Discord via Flatpak (more portable and updated on Flathub)
    - name: Install Discord
      community.general.flatpak:
        name: com.discordapp.Discord
        state: present
        remote: flathub

    # Install Microsoft Teams
    #- name: Install Microsoft Teams
    #  community.general.flatpak:
    #    name: com.microsoft.Teams
    #    state: present
    #    remote: flathub

    # Install Zoom
    - name: Install Zoom
      community.general.flatpak:
        name: us.zoom.Zoom
        state: present
        remote: flathub

