---
- name: Install communication apps
  hosts: all
  become: true
  tasks:
    # Install Discord
    - name: Install Discord
      ansible.builtin.apt:
        name: discord
        state: present

    # Install Microsoft Teams
    - name: Install Microsoft Teams
      community.general.flatpak:
        name: com.microsoft.Teams
        state: present
        remote: flathub

    # Install Zoom
    - name: Install Zoom
      community.general.flatpak:
        name: us.zoom.Zoom
        state: present
        remote: flathub

    # Install Skype
    - name: Install Skype
      community.general.flatpak:
        name: com.skype.Client
        state: present
        remote: flathub
