---
- name: Install communication apps
  hosts: all
  become: true
  tasks:
    # Update apt cache
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    # Install Discord
    - name: Install Discord
      ansible.builtin.apt:
        name: discord
        state: present

    # Install Microsoft Teams
    - name: Install Microsoft Teams
      ansible.builtin.apt:
        name: teams
        state: present

    # Install Zoom
    - name: Install Zoom
      ansible.builtin.apt:
        name: zoom
        state: present

    # Install Slack
    - name: Install Slack
      ansible.builtin.apt:
        name: slack
        state: present

    # Install Skype
    - name: Install Skype
      ansible.builtin.apt:
        name: skypeforlinux
        state: present
