- name: Install download tools
  hosts: all
  become: true
  tasks:
    - name: Install native tools
      ansible.builtin.apt:
        name:
          - transmission # A fast, efficient, and user-friendly torrent client
          - filezilla # A free, open-source FTP client for file transfers
          - aria2 # A lightweight multi-protocol & multi-source command-line download utility
          - wget # A free utility for non-interactive download of files from the web
          - curl # A command-line tool for transferring data with URL syntax
          - qbittorrent # A free and open-source BitTorrent client
        state: present
