---
- name: Install audio, video, and image related software
  hosts: all
  become: true
  tasks:
    # Install Flatpak packages (com.obsproject.Studio)
    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - com.obsproject.Studio # Video streamer / capturer

    # Install native video packages
    - name: Install video packages
      ansible.builtin.apt:
        pkg:
          - v4l2loopback-dkms # Kernel module for creating V4L2 loopback devices
          - libavcodec-extra # Additional codecs for libav
          - ffmpeg # Tool to convert multimedia formats
          - cheese # Webcam booth
          - kazam # Screen recording program
          - vlc # Multimedia player and streamer
        state: present

    # Install native audio packages
    - name: Install audio packages
      ansible.builtin.apt:
        pkg:
          - audacity # Audio editor and recorder
        state: present

    ############################################################
    # Spotify
    ############################################################
    - name: Download Spotify GPG key
      ansible.builtin.get_url:
        url: https://download.spotify.com/debian/pubkey_5E3C45D7B312C643.gpg
        dest: /usr/share/keyrings/spotify-archive-keyring.gpg
        mode: '0644'

    - name: Add Spotify apt repository (signed-by)
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64 signed-by=/usr/share/keyrings/spotify-archive-keyring.gpg] http://repository.spotify.com stable non-free'
        filename: spotify
        state: present
      register: spotify_repo
      failed_when: false

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes
        cache_valid_time: 0
      when: spotify_repo is defined

    - name: Install Spotify client
      ansible.builtin.apt:
        name: spotify-client
        state: present

    # Install native graphics packages
    - name: Install graphics packages
      ansible.builtin.apt:
        pkg:
          - krita # Digital painting program
          - gimp # GNU Image Manipulation Program
          - gimp-data # Data files for GIMP
          - gimp-plugin-registry # Plugins for GIMP
          - gimp-data-extras # Additional data files for GIMP
          - inkscape # Vector graphics editor
          - imagemagick # Image manipulation tool
          - flameshot # Powerful yet simple screenshot software
        state: present

    # Set VLC as default video/audio player
    - name: Set VLC as default video/audio player
      ansible.builtin.shell: |
        xdg-mime default vlc.desktop video/*
        xdg-mime default vlc.desktop audio/*
      args:
        executable: /bin/bash
