---
- name: Install software utilities
  hosts: all
  become: true
  tasks:
    # Install Flatpak packages
    - name: Install Flatpak packages
      community.general.flatpak:
        name:
          - org.gtk.Gtk3theme.Pop-dark # Enable GTK theme for Flatpak apps

    # Install native packages
    - name: Install native packages
      ansible.builtin.apt:
        pkg:
          # File and backup managers
          - nautilus-admin # Nautilus extension for administrative privileges
          - timeshift # System restore tool
          # Archive extractors
          - unace # Extractor for .ace files
          - unrar # Extractor for .rar files
          - zip # Zip file compression utility
          - unzip # Zip file decompression utility
          - p7zip-full # Full version of 7z compression utilities
          - p7zip-rar # 7z compression utilities for .rar files
          - sharutils # Utilities for manipulating shell archives
          - rar # Archive manager for .rar files
          - uudeview # Utility for encoding and decoding files
          - mpack # Utility for encoding and decoding messages
          - arj # Archiver for .arj files
          - cabextract # Extractor for Microsoft .cab files
          - file-roller # Archive manager for GNOME
          # File tools
          - mmv # Move/copy/append/link multiple files by wildcard patterns
          # Partition tools
          - gparted # GNOME partition editor
          - exfatprogs # Tools for exFAT filesystems
          - exfat-fuse # Filesystem in Userspace implementation for exFAT
          # Package installer
          - gdebi # Simple tool to install deb files
          # System info and monitor
          - neofetch # Command-line system information tool
          - htop # Interactive process viewer
          # Fonts
          - fonts-powerline # Powerline fonts for status lines and prompts
          - fonts-liberation # Fonts with the same metrics as Times, Arial, and Courier
        state: present

    # Powerline font
    - name: Download and install Menlo for Powerline font
      ansible.builtin.get_url:
        url: http://github.com/abertsch/Menlo-for-Powerline/blob/master/Menlo%20for%20Powerline.ttf?raw=true
        dest: /usr/share/fonts/

    - name: Update font cache
      ansible.builtin.command: fc-cache -vf /usr/share/fonts/

    # Install AppImage Launcher
    - name: Add AppImage Launcher PPA repository
      apt_repository:
        repo: 'ppa:appimagelauncher-team/stable'
        state: present

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install AppImage Launcher
      ansible.builtin.apt:
        pkg:
          - appimagelauncher
