---
- name: Install database tools
  hosts: all
  become: true
  tasks:
    # Update apt cache
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    # Install dependencies
    - name: Install dependencies
      ansible.builtin.apt:
        name:
          - wget
          - lsb-release
          - gnupg
        state: present

    # Install DBeaver - a universal  toola universal  tool
    - name: Install DBeaver
      ansible.builtin.apt:
        name: dbeaver
        state: present

    # Add MongoDB GPG key
    - name: Add MongoDB GPG key
      ansible.builtin.apt_key:
        url: https://www.mongodb.org/static/pgp/server-4.2.asc
        state: present

    # Add MongoDB repository
    - name: Add MongoDB repository
      ansible.builtin.apt_repository:
        repo: 'deb [arch=amd64] https://repo.mongodb.org/apt/ubuntu bionic/mongodb-org/4.2 multiverse'

    # Update apt cache after adding new repositories
    - name: Update apt cache after adding new repositories
      ansible.builtin.apt:
        update_cache: yes

    # Download and install latest MongoDB Compass
    - name: Download latest MongoDB Compass
      ansible.builtin.shell: |
        LATEST_COMPASS_VERSION=$(curl -sL https://www.mongodb.com/try/download/compass | grep -Po 'mongodb-compass_.*?_amd64.deb' | head -1)
        wget https://downloads.mongodb.com/compass/$LATEST_COMPASS_VERSION -O /tmp/mongodb-compass.deb
        apt install -y /tmp/mongodb-compass.deb
      args:
        executable: /bin/zsh
