---
- name: Install Git tools
  hosts: all
  become: true
  tasks:
    - name: Install native packages
      ansible.builtin.apt:
        name:
          - git-gui # Git GUI
          - tig # Text-mode interface for Git
          - git-cola # Powerful, user-friendly Git GUI
          - git-extras # Additional Git utilities
          - hub # GitHub CLI wrapper
          - stgit # Stack of patches on Git
          - meld # Visual diff and merge tool
          - gitk # Git repository browser
        state: present
