---
- name: Install all development playbooks and dependencies
  hosts: all
  become: false
  tasks:
    # Update apt cache
    - name: Update apt cache
      become: true
      ansible.builtin.apt:
        update_cache: yes

    # Install native packages
    - name: Install native packages
      become: true
      ansible.builtin.apt:
        pkg:
          - vim # Highly configurable text editor
          - code # TypeScript IDE from Microsoft
        state: present

    # Install JetBrains Toolbox
    - name: Install JetBrains Toolbox - manage all available JetBrains software
      become: true
      ansible.builtin.shell: |
        . /tmp/lib/misc.sh
        TOOLBOX_URL=$(curl --silent 'https://data.services.jetbrains.com/products/releases?code=TBA&latest=true&type=release' \
            -H 'Origin: https://www.jetbrains.com' \
            -H 'Accept-Encoding: gzip, deflate, br' \
            -H 'Accept-Language: en-US,en;q=0.8' \
            -H 'Accept: application/json, text/javascript, */*; q=0.01' \
            -H 'Referer: https://www.jetbrains.com/toolbox/download/' \
            -H 'Connection: keep-alive' \
            -H 'DNT: 1' \
            --compressed \
          | grep -Po '"linux":.*?[^\\]",' \
          | awk -F ':' '{print $3,":"$4}' | sed 's/[", ]//g')
        APP_IMAGE_FOLDER="$HOME/.local/bin"
        install -d "$APP_IMAGE_FOLDER"
        rm -rf "$APP_IMAGE_FOLDER/jetbrains-toolbox"
        curl -sL "$TOOLBOX_URL" | tar xvz --directory="$APP_IMAGE_FOLDER" --strip-components=1
        create-launcher-script $APP_IMAGE_FOLDER/jetbrains-toolbox $APP_IMAGE_FOLDER/jetbrains-toolbox.sh
        add-to-startup jetbrains-toolbox $APP_IMAGE_FOLDER/jetbrains-toolbox.sh
      args:
        executable: /bin/bash

    # Set VSCode as default text editor
    - name: Set VSCode as default text editor
      become: true
      ansible.builtin.shell: xdg-mime default code.desktop text/plain
      args:
        executable: /bin/bash

    # Restore VSCode settings
    - name: Restore VSCode settings
      become: true
      ansible.builtin.copy:
        src: ../../config/misc/vs-code-settings.json
        dest: ~/.config/Code/User/settings.json
