---
- name: Install virtualization tools
  hosts: all
  become: true
  tasks:
    # VirtualBox
    - name: Set VirtualBox license to true
      ansible.builtin.debconf:
        name: virtualbox-ext-pack
        question: virtualbox-ext-pack/license
        value: 'true'
        vtype: select

    - name: Install VirtualBox and related packages
      ansible.builtin.apt:
        pkg:
          - virtualbox # VirtualBox
          - virtualbox-dkms # VirtualBox DKMS
          - virtualbox-ext-pack # VirtualBox Extension Pack
          - virtualbox-guest-additions-iso # VirtualBox Guest Additions ISO
          - virtualbox-guest-utils # VirtualBox Guest Utilities
        state: present
        update_cache: yes

    # Docker
    - name: Add Docker repository key and APT source
      ansible.builtin.shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --yes --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo $VERSION_CODENAME) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        executable: /bin/bash

    - name: Install Docker and related packages
      ansible.builtin.apt:
        pkg:
          - docker-ce # Docker Community Edition
          - docker-ce-cli # Docker CLI
          - containerd.io # Container runtime
          - docker-buildx-plugin # Docker Buildx plugin
          - docker-compose-plugin # Docker Compose plugin
        state: present
        update_cache: yes

    - name: Add current user to Docker group
      ansible.builtin.user:
        name: '{{ ansible_user }}'
        groups: docker
        append: yes
        state: present

    - name: Fix permissions for Docker socket
      ansible.builtin.file:
        path: /var/run/docker.sock
        mode: '0666'
        state: file
