---
- name: Copy dotfiles to home directory
  hosts: all
  tasks:
    # Copy all configuration files under the dotfiles folder
    - name: Copy dotfiles
      ansible.builtin.copy:
        src: ../../config/dotfiles/
        dest: '{{ ansible_env.HOME }}/'
        owner: '{{ ansible_user }}'
        group: '{{ ansible_user }}'
        mode: '0644'
